{{- range .Values.nodepools }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .name }}
spec:
  role: {{ .role }}
  amiSelectorTerms:
    - alias: "{{ .amiAlias }}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  tags:
    karpenter.sh/discovery: ${cluster_name}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}
spec:
  template:
    metadata:
      labels:
        {{- toYaml .labels | nindent 8 }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .name }}
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: {{ .instanceCategories | toYaml | nindent 12 }}
        - key: karpenter.k8s.aws/instance-family
          operator: NotIn
          values: {{ .instanceFamilies | toYaml | nindent 12 }}
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["{{ .capacityType }}"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: {{ .instanceSizes | toYaml | nindent 12 }}
  limits:
    cpu: {{ .cpuLimits }}
    memory: {{ .memoryLimits }}
  {{- if .disruption }}
  disruption:
    {{- toYaml .disruption | nindent 4 }}
  {{- end }}
{{- end }}
