apiVersion: v2
name: istio-base
description: A Helm chart for deploying Istio base components
type: application
version: 0.1.0

dependencies:
- name: base
  version: "1.28.0"
  repository: "https://istio-release.storage.googleapis.com/charts"
