apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets-provider-class
  namespace: kube-system # Deploy in kube-system, or wherever the consuming pods are
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.dbSecretArn }} # This comes from the top-level value
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
  secretObjects:
    - secretName: db-secret # The name of the Kubernetes Secret to create
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
