apiVersion: v2
name: aws-lb-controller
description: A Helm chart for AWS Load Balancer Controller
type: application
version: 0.1.0
appVersion: "1.17.0" # Match the version used in Terraform

dependencies:
  - name: aws-load-balancer-controller
    version: "1.17.0" # Match the version used in Terraform
    repository: "https://aws.github.io/eks-charts"
