apiVersion: v2
name: mimir
description: Mimir metrics aggregation system
type: application
version: 1.0.0
appVersion: "2.12.0"
dependencies:
  - name: mimir-distributed
    version: "5.5.1"
    repository: "https://grafana.github.io/helm-charts"

