apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredNamespaceLabel
metadata:
  name: nodepool-selector-must-match-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system", "gatekeeper-system"]
  parameters:
    label: "nodepool"
