apiVersion: v2
name: alloy
description: A Helm chart for Grafana Alloy
type: application
version: 0.1.0

dependencies:
  - name: alloy
    version: "0.1.0" # This will be the first version, but it is a well tested version
    repository: "https://grafana.github.io/helm-charts"
