apiVersion: v2
name: secrets-store-csi-driver
description: A Helm chart for Secrets Store CSI Driver
type: application
version: 0.1.0
appVersion: "1.3.4" # Match the version used in Terraform

dependencies:
  - name: secrets-store-csi-driver
    version: "1.3.4" # Match the version used in Terraform
    repository: "https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts"