apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: ai-sre
spec:
  ai:
    enabled: true
    model: ggml-gpt4all-j.bin
    backend: localai
    baseUrl: http://locaai.ai-sre.svc.cluster.local:8080/v1
  noCache: false
  version: v0.3.41
