apiVersion: v2
name: loki
description: Loki log aggregation system
type: application
version: 1.0.0
appVersion: "2.9.0"
dependencies:
  - name: loki
    version: "6.19.0"
    repository: "https://grafana.github.io/helm-charts"

